### ISSUE TITLE
Shell doesn't start on Windows.

### ISSUE THREAD

**Issue by acedron** [sahito-org/cli#5]
Error:

```
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at afterWriteDispatched (internal/stream_base_commons.js:154:25)
    at writeGeneric (internal/stream_base_commons.js:145:3)
    at ReadStream.Socket._writeGeneric (net.js:786:11)
    at ReadStream.Socket._write (net.js:798:8)
    at doWrite (_stream_writable.js:403:12)
    at writeOrBuffer (_stream_writable.js:387:5)
    at ReadStream.Writable.write (_stream_writable.js:318:11)
    at cursorTo (readline.js:1195:17)
    at Interface._refreshLine (readline.js:385:3)
    at Interface.prompt (readline.js:301:10)
Emitted 'error' event on ReadStream instance at:
    at errorOrDestroy (internal/streams/destroy.js:108:12)
    at onwriteError (_stream_writable.js:418:5)
    at onwrite (_stream_writable.js:445:5)
    at internal/streams/destroy.js:50:7
    at ReadStream.Socket._destroy (net.js:679:5)
    at ReadStream.destroy (internal/streams/destroy.js:38:8)
    at afterWriteDispatched (internal/stream_base_commons.js:154:17)
    at writeGeneric (internal/stream_base_commons.js:145:3)
    at ReadStream.Socket._writeGeneric (net.js:786:11)
    at ReadStream.Socket._write (net.js:798:8) {
  errno: 'EPIPE',
  code: 'EPIPE',
  syscall: 'write'
```

**Comment by acedron** [comment]
Seems fixed.
Probably fixed in #6 and [v0.1.2](https://github.com/sahito-org/cli/releases/tag/v0.1.2)
